Chore/update googleapi scopes
zilinj88/nextjs-mailmerge pull request #9
Opened 2024-01-16 15:13 UTC by zilinj88

2024-01-16 18:43 UTC, tianhuil requested changes
Some feedback

2024-01-16 18:43 UTC, tianhuil commented on components/users-table.tsx
> +  const selectRow = (index: number) => {
1. Should we wrap this in `React.useCallback`?
2. Do you need to pass `index`?

2024-01-16 18:43 UTC, tianhuil commented on lib/token.ts
> +        'https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly',
1. Just to make sure, did you test this?
2. Why do you need to be able to read emails?  We are only sending emails right?

2024-01-16 18:45 UTC, codemage8 commented on components/users-table.tsx
> +  const selectRow = (index: number) => {
Sorry, I was too haste,  I don't think we need to pass `index`. I'll fix that

2024-01-16 18:49 UTC, codemage8 commented on lib/token.ts
> +        'https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly',
> 1. Just to make sure, did you test this?
> 2. Why do you need to be able to read emails?  We are only sending emails right?

1.  I tested it, and it could read the user's email
2. As we discussed [here](https://www.notion.so/Open-source-mailmerge-d7e2e20c921b49efb6718b938cc63f98?pvs=4#ca992e7e40b14ab08a522c2555965017),  and from the [google documentation](https://developers.google.com/gmail/api/reference/rest/v1/users/getProfile#authorization-scopes), we need extra scope to get currently logged-in user's profile.
I think we can restrict to gmail.metadata (currently I used gmail.readonly)
https://www.googleapis.com/auth/gmail.readonly
https://www.googleapis.com/auth/gmail.metadata

2024-01-16 18:55 UTC, tianhuil requested changes

2024-01-16 18:55 UTC, tianhuil commented on lib/token.ts
> +        'https://www.googleapis.com/auth/gmail.send https://www.googleapis.com/auth/gmail.readonly',
Regarding the scopes, I think we can do something more narrowly tailored: https://stackoverflow.com/a/41707446/8930600

Also, see https://developers.google.com/identity/openid-connect/openid-connect?hl=en#scope-param

2024-01-17 23:00 UTC, tianhuil approved these changes

2024-01-17 23:00 UTC, merged